models:
  - MantisV2
  - TabPFN
  - TabPFN-TS
  - TabICL
  - TabICLForecaster
  - MOMENT
  - TiRex
  - Chronos2
  - LeNEPA-Aiono
  - LeNEPA-CauKer2M
  - TTM
  - Moirai
  - Toto
  - TiViT-H
  - TiConvNext
  - NuTime
  - T-Loss
